services:
  backend_dev:
    container_name: backend_dev
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "8000:8000"
    env_file:
      - env/.env.dev
    depends_on:
      - database_dev

  redis_dev:
    container_name: redis_dev
    build:
      context: .
      dockerfile: ./compose/redis/Dockerfile
    ports:
      - "6379:6379"

  database_dev:
    container_name: database_dev
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - database_volume_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - env/.env.dev

  elasticsearch_dev:
    container_name: elasticsearch_dev
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"  # ElasticSearch REST API port
      - "9300:9300"  # ElasticSearch transport port
    volumes:
      - es_data:/usr/share/elasticsearch/data  # Persistent storage for ElasticSearch

  kibana_dev:
    container_name: kibana_dev
    image: docker.elastic.co/kibana/kibana:8.10.2
    depends_on:
      - elasticsearch_dev
    ports:
      - "5601:5601"
    env_file:
      - env/.env.dev

volumes:
  database_volume_dev:
  es_data: