# Generated by Django 4.2.16 on 2024-11-14 13:00
import os

from django.db import migrations


def create_default_superuser(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserProfile = apps.get_model("users", "UserProfile")

    admin_email = os.getenv("DJANGO_ADMIN_EMAIL", "admin@yourdomain.com")
    admin_user = os.getenv("DJANGO_ADMIN_USER", "django_admin_prod")
    admin_password = os.getenv("DJANGO_ADMIN_PASSWORD", "secure-production-password")
    admin_first_name = "Default"
    admin_last_name = "Admin"

    user = User.objects.create_superuser(
        username=admin_user,
        email=admin_email,
        password=admin_password,
        first_name=admin_first_name,
        last_name=admin_last_name,
    )

    UserProfile.objects.create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_superuser),
    ]
