# Generated by Django 3.2.25 on 2024-10-08 02:50

import os
from django.db import migrations


def create_initial_categories_and_products(apps, schema_editor):
    # Get the models
    Category = apps.get_model('store', 'Category')
    Product = apps.get_model('store', 'Product')

    # Create some initial categories
    laptops = Category.objects.create(name="Laptops", description="Various laptop brands and models")
    phones = Category.objects.create(name="Smartphones", description="Latest smartphones from popular brands")
    accessories = Category.objects.create(name="Accessories", description="Phone and laptop accessories")

    # Create some initial products
    Product.objects.create(
        category=laptops,
        name="MacBook Air 13\"",
        description="The latest MacBook Air with M2 chip, 13-inch Retina display.",
        price=1099.00,
        quantity_stock=50
    )

    Product.objects.create(
        category=phones,
        name="iPhone 15 Pro",
        description="Apple's latest smartphone with advanced camera features.",
        price=1299.00,
        quantity_stock=100
    )

    Product.objects.create(
        category=accessories,
        name="Logitech MX Master 3 Mouse",
        description="High precision wireless mouse, ideal for work and gaming.",
        price=99.00,
        quantity_stock=200
    )


def create_default_superuser(apps, schema_editor):
    # Get the User model from the app registry
    User = apps.get_model('auth', 'User')

    # Fetch environment variables for the superuser credentials
    admin_email = os.getenv('DJANGO_ADMIN_EMAIL', 'admin@example.com')
    admin_user = os.getenv('DJANGO_ADMIN_USER', 'django_admin_user')
    admin_password = os.getenv('DJANGO_ADMIN_PASSWORD', 'django_admin_password')

    # Create a default superuser with environment variables
    User.objects.create_superuser(
        username=admin_user,  # Superuser username from environment
        email=admin_email,    # Superuser email from environment
        password=admin_password  # Superuser password from environment
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),  # Ensure this matches your previous migration file
    ]

    operations = [
        migrations.RunPython(create_initial_categories_and_products),  # Create categories and products
        migrations.RunPython(create_default_superuser),  # Create the superuser
    ]
