services:
  backend_dev:
    container_name: backend_dev
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "8000:8000"
    env_file:
      - env/.env.dev
    depends_on:
      - database_dev

  database_dev:
    container_name: database_dev
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    expose:
      - 5432
    volumes:
      - database_volume_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - env/.env.dev

volumes:
  database_volume_dev: